[package]
name = "client"
version = "0.1.0"
authors = ["Denis Lavrov <bahus.vel@gmail.com>"]
build = "build.rs"

[dependencies]
net2 = "0.2"
common = {path = "../common"}

[build-dependencies]
cc = "1.0"
