[package]
name = "fs"
version = "0.1.0"
authors = ["Denis Lavrov <bahus.vel@gmail.com>"]
build = "build.rs"

[dependencies]
net2 = "0.2"
lazy_static = "1.0.0"
common = {path = "../common"}
zstd = "0.4.14"

[build-dependencies]
cc = "1.0"
