[package]
name = "fuse"
version = "0.1.0"
authors = ["Denis Lavrov <bahus.vel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.60"

[build-dependencies]
bindgen = "0.50"