[package]
name = "fsyncd"
version = "0.1.0"
authors = ["Denis Lavrov <bahus.vel@gmail.com>"]
build = "build.rs"

[dependencies]
net2 = "0.2"
lazy_static = "1.0.0"
clap = "2.29.0"
zstd = "0.4.14"
dssc = { path = "../dssc" }

[build-dependencies]
cc = "1.0"
